name: CI

on: [push, pull_request]

jobs:
    updatron-only:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2
            
            - name: Tester uniquement Updatron
              run: rm  !(updatron.sk)

            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
              with:
                  addons: |
                    SkQuery-Lime
                    Skent
    updatron-tntrace:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2
            
            - name: Retirer les scripts inutiles du test
              run: rm  !(updatron.sk|tntrace.sk)
              
            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
              with:
                  addons: |
                    SkQuery-Lime
                    Skent
    updatron-sprint-racers:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2
            
            - name: Retirer les scripts inutiles du test
              run: rm  !(updatron.sk|sprint-racers.sk)
              
            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
              with:
                  addons: |
                    SkQuery-Lime
                    Skent
    updatron-cc2:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2
            
            - name: Retirer les scripts inutiles du test
              run: rm  !(updatron.sk|cc2.sk)
              
            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
              with:
                  addons: |
                    SkQuery-Lime
                    Skent
                    
    updatron-ariane5:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2
            
            - name: Retirer les scripts inutiles du test
              run: rm  !(updatron.sk|ariane5.sk)
              
            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
              with:
                  addons: |
                    SkQuery-Lime
                    Skent
