name: Updatron

on: [push, pull_request]

jobs:
    updatron:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2
            
            - name: Tester uniquement Updatron
              run: cp scripts/updatron.sk .

            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
              with:
                  addons: |
                    SkQuery-Lime
                    Skent
